// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OisGschaut.API.Data;

#nullable disable

namespace OisGschaut.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("OisGschaut.API.Models.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Poster"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Backdrop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Still"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Logo"
                        });
                });

            modelBuilder.Entity("OisGschaut.API.Models.CollaboratorRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CollaboratorRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Owner",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Editor",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Viewer",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("OisGschaut.API.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("OisGschaut.API.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberInSeason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "Season", "NumberInSeason")
                        .IsUnique();

                    b.ToTable("Episodes", t =>
                        {
                            t.HasCheckConstraint("ck_episodes_number_positive", "NumberInSeason > 0");

                            t.HasCheckConstraint("ck_episodes_season_positive", "Season > 0");
                        });
                });

            modelBuilder.Entity("OisGschaut.API.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("OisGschaut.API.Models.ListCollaborator", b =>
                {
                    b.Property<int>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CollaboratorRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvitedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ListId", "UserId");

                    b.HasIndex("CollaboratorRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("ListCollaborators");
                });

            modelBuilder.Entity("OisGschaut.API.Models.ListItem", b =>
                {
                    b.Property<int>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("ListId", "MediaId");

                    b.HasIndex("MediaId");

                    b.HasIndex("MediaTypeId");

                    b.ToTable("ListItems");
                });

            modelBuilder.Entity("OisGschaut.API.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plot")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuntimeMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvMazeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MediaTypeId");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.HasIndex("TvMazeId")
                        .IsUnique();

                    b.ToTable("Media");
                });

            modelBuilder.Entity("OisGschaut.API.Models.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("MediaId", "AssetTypeId", "Url")
                        .IsUnique();

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("OisGschaut.API.Models.MediaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Movie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TV Show"
                        });
                });

            modelBuilder.Entity("OisGschaut.API.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RatingSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Score")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RatingSourceId");

                    b.HasIndex("MediaId", "RatingSourceId")
                        .IsUnique();

                    b.ToTable("Ratings", t =>
                        {
                            t.HasCheckConstraint("ck_ratings_score_range", "Score >= 0 AND Score <= 10");
                        });
                });

            modelBuilder.Entity("OisGschaut.API.Models.RatingSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RatingSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TMDB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IMDb"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rotten Tomatoes"
                        });
                });

            modelBuilder.Entity("OisGschaut.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("OAuthId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OAuthProvider")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OisGschaut.API.Models.UserList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("OisGschaut.API.Models.Comment", b =>
                {
                    b.HasOne("OisGschaut.API.Models.UserList", "List")
                        .WithMany("Comments")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OisGschaut.API.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OisGschaut.API.Models.Episode", b =>
                {
                    b.HasOne("OisGschaut.API.Models.Media", "Media")
                        .WithMany("Episodes")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("OisGschaut.API.Models.ListCollaborator", b =>
                {
                    b.HasOne("OisGschaut.API.Models.CollaboratorRole", "CollaboratorRole")
                        .WithMany("ListCollaborators")
                        .HasForeignKey("CollaboratorRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OisGschaut.API.Models.UserList", "List")
                        .WithMany("Collaborators")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OisGschaut.API.Models.User", "User")
                        .WithMany("Collaborations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollaboratorRole");

                    b.Navigation("List");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OisGschaut.API.Models.ListItem", b =>
                {
                    b.HasOne("OisGschaut.API.Models.UserList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OisGschaut.API.Models.Media", "Media")
                        .WithMany("ListItems")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OisGschaut.API.Models.MediaType", "MediaType")
                        .WithMany("ListItems")
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("Media");

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("OisGschaut.API.Models.Media", b =>
                {
                    b.HasOne("OisGschaut.API.Models.Genre", "Genre")
                        .WithMany("Media")
                        .HasForeignKey("GenreId");

                    b.HasOne("OisGschaut.API.Models.MediaType", "MediaType")
                        .WithMany("Media")
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("OisGschaut.API.Models.MediaAsset", b =>
                {
                    b.HasOne("OisGschaut.API.Models.AssetType", "AssetType")
                        .WithMany("MediaAssets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OisGschaut.API.Models.Media", "Media")
                        .WithMany("Assets")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("OisGschaut.API.Models.Rating", b =>
                {
                    b.HasOne("OisGschaut.API.Models.Media", "Media")
                        .WithMany("Ratings")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OisGschaut.API.Models.RatingSource", "RatingSource")
                        .WithMany("Ratings")
                        .HasForeignKey("RatingSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("RatingSource");
                });

            modelBuilder.Entity("OisGschaut.API.Models.UserList", b =>
                {
                    b.HasOne("OisGschaut.API.Models.User", "User")
                        .WithMany("Lists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OisGschaut.API.Models.AssetType", b =>
                {
                    b.Navigation("MediaAssets");
                });

            modelBuilder.Entity("OisGschaut.API.Models.CollaboratorRole", b =>
                {
                    b.Navigation("ListCollaborators");
                });

            modelBuilder.Entity("OisGschaut.API.Models.Genre", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("OisGschaut.API.Models.Media", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Episodes");

                    b.Navigation("ListItems");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("OisGschaut.API.Models.MediaType", b =>
                {
                    b.Navigation("ListItems");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("OisGschaut.API.Models.RatingSource", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("OisGschaut.API.Models.User", b =>
                {
                    b.Navigation("Collaborations");

                    b.Navigation("Comments");

                    b.Navigation("Lists");
                });

            modelBuilder.Entity("OisGschaut.API.Models.UserList", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("Comments");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
